spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service # service name
          predicates:
            - Path=/user-service/** # url pattern
        - id: log-service
          uri: lb://log-service
          predicates:
            - Path=/log-service/**
        - id: mailbox-service
          uri: lb://mailbox-service
          predicates:
            - Path=/mailbox-service/**
        - id: authentication-server
          uri: lb://authentication-server
          predicates:
            - Path=/authentication-server/**

server:
  port: 8090

#The Gateway will also be registered at the Eureka server
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
